# Generated by Django 5.1 on 2024-11-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_staticcontentclass_title_alter_contactclass_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='staticphotoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='photo')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
