# Generated by Django 5.1 on 2025-01-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_workshopclass_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopclass',
            name='title',
        ),
    ]
