# Generated by Django 5.1 on 2025-01-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_workshopclass_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopclass',
            name='category',
        ),
    ]
