# Generated by Django 5.1 on 2024-11-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_staticcontentclass_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticphotoclass',
            name='key',
            field=models.CharField(max_length=15),
        ),
    ]
