# Generated by Django 5.1 on 2024-11-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_staticphotoclass_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopclass',
            name='startw',
            field=models.DateField(),
        ),
    ]
