# Generated by Django 5.1 on 2025-01-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_workshopclass_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopclass',
            name='remainingparticipants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
