# Generated by Django 5.1 on 2024-11-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_workshopclass_startw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshopclass',
            old_name='category',
            new_name='categoryw',
        ),
    ]
