# Generated by Django 5.1 on 2025-01-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_orderclass_orderitemclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemclass',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
