# Generated by Django 5.1 on 2024-11-21 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_category_workshopclass_categoryw'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopclass',
            name='categoryS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs', to='main_app.categoryclass'),
        ),
        migrations.AlterField(
            model_name='workshopclass',
            name='categoryw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c', to='main_app.categorywsclass'),
        ),
    ]
