# Generated by Django 5.1 on 2025-01-04 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_orderitemclass_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopclass',
            name='service',
            field=models.ForeignKey(limit_choices_to={'category__title': 'برگزاری کارگاه'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srv', to='main_app.serviceclass'),
        ),
    ]
