# Generated by Django 5.1 on 2024-11-21 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_workshopclass_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopclass',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c', to='main_app.categoryclass'),
        ),
        migrations.AlterField(
            model_name='workshopclass',
            name='categoryw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cw', to='main_app.categorywsclass'),
        ),
    ]
