# Generated by Django 5.1 on 2025-01-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_reservationclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleclass',
            name='price',
            field=models.IntegerField(default='380000'),
        ),
        migrations.AlterField(
            model_name='reservationclass',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap', to='main_app.appointmentclass', verbose_name='قرار ملاقات'),
        ),
    ]
