# Generated by Django 5.1 on 2024-11-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_workshopclass_category_alter_workshopclass_categoryw'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapeutistClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('img', models.ImageField(upload_to='photo')),
                ('degree', models.CharField(max_length=50)),
            ],
        ),
    ]
