# Generated by Django 5.1 on 2024-11-24 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_therapeutistclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapeutistclass',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='main_app.serviceclass'),
        ),
        migrations.CreateModel(
            name='availabilityClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'دوشنبه'), ('Tuesday', 'سه\u200cشنبه'), ('Wednesday', 'چهارشنبه'), ('Thursday', 'پنج\u200cشنبه'), ('Friday', 'جمعه'), ('Saturday', 'شنبه'), ('Sunday', 'یک\u200cشنبه')], max_length=10, verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('therapeutist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='main_app.therapeutistclass')),
            ],
        ),
    ]
