# Generated by Django 5.1 on 2025-01-26 14:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_scheduleclass_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='articleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('authors', models.CharField(max_length=100, verbose_name='نویسندگان')),
                ('abstract', ckeditor.fields.RichTextField(verbose_name='چکیده')),
                ('file_pdf', models.FileField(upload_to='articles/pdfs/', verbose_name='فایل مقاله (PDF)')),
            ],
        ),
        migrations.AlterField(
            model_name='contactclass',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactclass',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactclass',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='contactclass',
            name='username',
            field=models.CharField(max_length=50, verbose_name='نام کاربری'),
        ),
    ]
