# Generated by Django 5.1 on 2025-01-26 21:01

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_articleclass_alter_contactclass_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicInfoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام کلینیک')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phoneNumber', models.CharField(max_length=20, verbose_name='شماره تلفن ثابت')),
                ('mobileNumber', models.CharField(max_length=20, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/logo/', verbose_name='لوگو')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='لینک یوتیوب')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینک لینکدین')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='لینک فیسبوک')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='لینک توییتر')),
            ],
        ),
        migrations.AlterModelOptions(
            name='articleclass',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='scheduleclass',
            options={'verbose_name': 'برنامه زمانبندی ', 'verbose_name_plural': ' برنامه های زمانبندی '},
        ),
        migrations.AlterModelOptions(
            name='therapeutistclass',
            options={'verbose_name': 'درمانگر', 'verbose_name_plural': 'درمانگران'},
        ),
        migrations.AlterField(
            model_name='categoryclass',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='categorywsclass',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='scheduleclass',
            name='price',
            field=models.IntegerField(default='380000', verbose_name='هزینه مشاوره'),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.categoryclass', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='serviceclass',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='staticcontentclass',
            name='key',
            field=models.CharField(max_length=15, verbose_name='کلید'),
        ),
        migrations.AlterField(
            model_name='staticcontentclass',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='staticcontentclass',
            name='txt',
            field=ckeditor.fields.RichTextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='staticphotoclass',
            name='img',
            field=models.ImageField(upload_to='photo', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='staticphotoclass',
            name='key',
            field=models.CharField(max_length=15, verbose_name='کلید'),
        ),
        migrations.AlterField(
            model_name='staticphotoclass',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='therapeutistclass',
            name='degree',
            field=models.CharField(max_length=50, verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='therapeutistclass',
            name='img',
            field=models.ImageField(upload_to='photo', verbose_name='عکس پرسنلی'),
        ),
        migrations.AlterField(
            model_name='therapeutistclass',
            name='name',
            field=models.CharField(max_length=35, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='therapeutistclass',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='therapists', to='main_app.serviceclass', verbose_name='خدمات'),
        ),
        migrations.AlterField(
            model_name='workshopclass',
            name='categoryw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cw', to='main_app.categorywsclass', verbose_name='طیقه بندی'),
        ),
        migrations.AlterField(
            model_name='workshopclass',
            name='img',
            field=models.ImageField(null=True, upload_to='photo', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='workshopclass',
            name='numbparticipants',
            field=models.CharField(max_length=30, verbose_name='تعداد شرکت کنندگان'),
        ),
        migrations.AlterField(
            model_name='workshopclass',
            name='numbsession',
            field=models.CharField(max_length=50, verbose_name='تعداد جلسات'),
        ),
        migrations.AlterField(
            model_name='workshopclass',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='workshopclass',
            name='remainingparticipants',
            field=models.PositiveIntegerField(default=0, verbose_name='ظرفیت باقیمانده'),
        ),
        migrations.AlterField(
            model_name='workshopclass',
            name='service',
            field=models.ForeignKey(limit_choices_to={'category__title': 'برگزاری کارگاه'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srv', to='main_app.serviceclass', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='workshopclass',
            name='startw',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
    ]
