# Generated by Django 5.1 on 2024-11-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_therapeutistclass_service_availabilityclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='availabilityClass',
        ),
    ]
