# Generated by Django 5.1 on 2025-01-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_clinicinfoclass_alter_articleclass_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicinfoclass',
            name='phoneNumber',
            field=models.CharField(max_length=20, null=True, verbose_name='شماره تلفن ثابت'),
        ),
    ]
