# Generated by Django 5.1 on 2025-02-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_clinicinfoclass_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationclass',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='reservationclass',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='رسید پرداخت'),
        ),
        migrations.AddField(
            model_name='reservationclass',
            name='payment_tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد رهگیری پرداخت'),
        ),
        migrations.AlterField(
            model_name='reservationclass',
            name='status',
            field=models.CharField(choices=[('cart', 'سبد خرید'), ('pending', 'در انتظار تأیید'), ('final', 'سفارش نهایی')], default='cart', max_length=20),
        ),
    ]
