# Generated by Django 5.1 on 2024-11-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_schedule_scheduleclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapeutistclass',
            name='service',
        ),
        migrations.AddField(
            model_name='therapeutistclass',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='therapists', to='main_app.serviceclass'),
        ),
    ]
