# Generated by Django 5.1 on 2025-02-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_reservationclass_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationclass',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationclass',
            name='status',
            field=models.CharField(choices=[('cart', 'سبد خرید'), ('pending', ' در انتظار تأیید ادمین'), ('final', 'سفارش نهایی'), ('expired', 'منقضی شده')], default='cart', max_length=20),
        ),
    ]
