# Generated by Django 5.1 on 2024-11-25 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_therapeutistclass_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetime', to='main_app.scheduleclass')),
                ('end_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etime', to='main_app.scheduleclass')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='main_app.serviceclass')),
                ('start_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stime', to='main_app.scheduleclass')),
                ('therapeutist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapeutist', to='main_app.therapeutistclass')),
            ],
        ),
    ]
