# Generated by Django 5.1 on 2025-02-01 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_reservationclass_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationclass',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='reservationclass',
            name='admin_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservationclass',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservationclass',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='reservationclass',
            name='payment_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
