# Generated by Django 5.1 on 2024-12-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_appointmentclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=50)),
                ('ussername', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.IntegerField(max_length=11)),
                ('address', models.CharField(max_length=250)),
                ('passw', models.CharField(max_length=16)),
                ('confirmpassw', models.CharField(max_length=16)),
            ],
        ),
    ]
