# Generated by Django 5.1 on 2025-02-03 09:34

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_scheduleclass_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopclass',
            name='startw',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ شروع'),
        ),
    ]
