# Generated by Django 5.1 on 2024-12-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_rename_ussername_registerclass_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentclass',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='main_app.scheduleclass'),
        ),
        migrations.AlterField(
            model_name='appointmentclass',
            name='date',
            field=models.DateField(default=None, null=True, verbose_name='تاریخ حضور'),
        ),
        migrations.AlterField(
            model_name='appointmentclass',
            name='end_time',
            field=models.TimeField(default=None, null=True, verbose_name='زمان پایان حضور'),
        ),
        migrations.AlterField(
            model_name='appointmentclass',
            name='start_time',
            field=models.TimeField(default=None, null=True, verbose_name='زمان شروع حضور'),
        ),
    ]
