# Generated by Django 5.1 on 2024-12-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_appointmentclass_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentclass',
            name='date',
            field=models.DateField(default=None, verbose_name='تاریخ حضور'),
        ),
    ]
