# Generated by Django 5.1 on 2024-12-11 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_appointmentclass_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentclass',
            name='service',
        ),
        migrations.AddField(
            model_name='appointmentclass',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='main_app.categoryclass'),
        ),
        migrations.AlterField(
            model_name='appointmentclass',
            name='end_time',
            field=models.TimeField(default=None, verbose_name='زمان پایان حضور'),
        ),
        migrations.AlterField(
            model_name='appointmentclass',
            name='start_time',
            field=models.TimeField(default=None, verbose_name='زمان شروع حضور'),
        ),
    ]
